<?xml version="1.0" encoding="UTF-8" ?>
<Package name="顔登録サンプル" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="" src="lib/.DS_Store" />
        <File name="__init__" src="lib/boto3/__init__.py" />
        <File name="compat" src="lib/boto3/compat.py" />
        <File name="resources-1" src="lib/boto3/data/cloudformation/2010-05-15/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/cloudwatch/2010-08-01/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/dynamodb/2012-08-10/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/ec2/2014-10-01/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/ec2/2015-03-01/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/ec2/2015-04-15/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/ec2/2015-10-01/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/ec2/2016-04-01/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/ec2/2016-09-15/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/ec2/2016-11-15/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/glacier/2012-06-01/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/iam/2010-05-08/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/opsworks/2013-02-18/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/s3/2006-03-01/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/sns/2010-03-31/resources-1.json" />
        <File name="resources-1" src="lib/boto3/data/sqs/2012-11-05/resources-1.json" />
        <File name="__init__" src="lib/boto3/docs/__init__.py" />
        <File name="action" src="lib/boto3/docs/action.py" />
        <File name="attr" src="lib/boto3/docs/attr.py" />
        <File name="base" src="lib/boto3/docs/base.py" />
        <File name="client" src="lib/boto3/docs/client.py" />
        <File name="collection" src="lib/boto3/docs/collection.py" />
        <File name="docstring" src="lib/boto3/docs/docstring.py" />
        <File name="method" src="lib/boto3/docs/method.py" />
        <File name="resource" src="lib/boto3/docs/resource.py" />
        <File name="service" src="lib/boto3/docs/service.py" />
        <File name="subresource" src="lib/boto3/docs/subresource.py" />
        <File name="utils" src="lib/boto3/docs/utils.py" />
        <File name="waiter" src="lib/boto3/docs/waiter.py" />
        <File name="__init__" src="lib/boto3/dynamodb/__init__.py" />
        <File name="conditions" src="lib/boto3/dynamodb/conditions.py" />
        <File name="table" src="lib/boto3/dynamodb/table.py" />
        <File name="transform" src="lib/boto3/dynamodb/transform.py" />
        <File name="types" src="lib/boto3/dynamodb/types.py" />
        <File name="__init__" src="lib/boto3/ec2/__init__.py" />
        <File name="createtags" src="lib/boto3/ec2/createtags.py" />
        <File name="deletetags" src="lib/boto3/ec2/deletetags.py" />
        <File name="exceptions" src="lib/boto3/exceptions.py" />
        <File name="__init__" src="lib/boto3/resources/__init__.py" />
        <File name="action" src="lib/boto3/resources/action.py" />
        <File name="base" src="lib/boto3/resources/base.py" />
        <File name="collection" src="lib/boto3/resources/collection.py" />
        <File name="factory" src="lib/boto3/resources/factory.py" />
        <File name="model" src="lib/boto3/resources/model.py" />
        <File name="params" src="lib/boto3/resources/params.py" />
        <File name="response" src="lib/boto3/resources/response.py" />
        <File name="__init__" src="lib/boto3/s3/__init__.py" />
        <File name="inject" src="lib/boto3/s3/inject.py" />
        <File name="transfer" src="lib/boto3/s3/transfer.py" />
        <File name="session" src="lib/boto3/session.py" />
        <File name="utils" src="lib/boto3/utils.py" />
        <File name="__init__" src="lib/botocore/__init__.py" />
        <File name="args" src="lib/botocore/args.py" />
        <File name="auth" src="lib/botocore/auth.py" />
        <File name="awsrequest" src="lib/botocore/awsrequest.py" />
        <File name="client" src="lib/botocore/client.py" />
        <File name="compat" src="lib/botocore/compat.py" />
        <File name="config" src="lib/botocore/config.py" />
        <File name="configloader" src="lib/botocore/configloader.py" />
        <File name="credentials" src="lib/botocore/credentials.py" />
        <File name="_retry" src="lib/botocore/data/_retry.json" />
        <File name="examples-1" src="lib/botocore/data/acm/2015-12-08/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/acm/2015-12-08/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/acm/2015-12-08/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/alexaforbusiness/2017-11-09/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/alexaforbusiness/2017-11-09/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/apigateway/2015-07-09/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/apigateway/2015-07-09/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/apigateway/2015-07-09/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/application-autoscaling/2016-02-06/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/application-autoscaling/2016-02-06/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/application-autoscaling/2016-02-06/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/appstream/2016-12-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/appstream/2016-12-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/appstream/2016-12-01/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/appsync/2017-07-25/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/appsync/2017-07-25/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/athena/2017-05-18/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/athena/2017-05-18/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/autoscaling/2011-01-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/autoscaling/2011-01-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/autoscaling/2011-01-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/batch/2016-08-10/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/batch/2016-08-10/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/batch/2016-08-10/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/budgets/2016-10-20/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/budgets/2016-10-20/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/budgets/2016-10-20/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/ce/2017-10-25/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ce/2017-10-25/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloud9/2017-09-23/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloud9/2017-09-23/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/clouddirectory/2016-05-10/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/clouddirectory/2016-05-10/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/cloudformation/2010-05-15/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudformation/2010-05-15/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudformation/2010-05-15/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudformation/2010-05-15/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2014-05-31/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2014-05-31/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2014-05-31/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2014-10-21/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2014-10-21/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2014-10-21/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2014-11-06/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2014-11-06/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2014-11-06/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2015-04-17/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2015-04-17/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2015-04-17/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2015-07-27/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2015-07-27/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2015-07-27/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2015-09-17/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2015-09-17/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2015-09-17/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2016-01-13/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2016-01-13/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2016-01-13/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2016-01-28/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2016-01-28/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2016-01-28/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2016-08-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2016-08-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2016-08-01/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2016-08-20/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2016-08-20/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2016-08-20/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2016-09-07/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2016-09-07/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2016-09-07/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2016-09-29/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2016-09-29/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2016-09-29/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/cloudfront/2016-11-25/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2016-11-25/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2016-11-25/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2016-11-25/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/cloudfront/2017-03-25/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudfront/2017-03-25/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudfront/2017-03-25/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudfront/2017-03-25/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/cloudhsm/2014-05-30/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudhsm/2014-05-30/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudhsm/2014-05-30/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudhsmv2/2017-04-28/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudhsmv2/2017-04-28/service-2.json" />
        <File name="service-2" src="lib/botocore/data/cloudsearch/2011-02-01/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudsearch/2013-01-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudsearch/2013-01-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/cloudsearchdomain/2013-01-01/examples-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudsearchdomain/2013-01-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/cloudtrail/2013-11-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudtrail/2013-11-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudtrail/2013-11-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/cloudwatch/2010-08-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/cloudwatch/2010-08-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cloudwatch/2010-08-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/cloudwatch/2010-08-01/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/codebuild/2016-10-06/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/codebuild/2016-10-06/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/codebuild/2016-10-06/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/codecommit/2015-04-13/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/codecommit/2015-04-13/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/codecommit/2015-04-13/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/codedeploy/2014-10-06/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/codedeploy/2014-10-06/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/codedeploy/2014-10-06/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/codedeploy/2014-10-06/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/codepipeline/2015-07-09/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/codepipeline/2015-07-09/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/codepipeline/2015-07-09/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/codestar/2017-04-19/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/codestar/2017-04-19/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/cognito-identity/2014-06-30/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/cognito-identity/2014-06-30/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cognito-identity/2014-06-30/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/cognito-idp/2016-04-18/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/cognito-idp/2016-04-18/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cognito-idp/2016-04-18/service-2.json" />
        <File name="service-2" src="lib/botocore/data/cognito-sync/2014-06-30/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/comprehend/2017-11-27/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/comprehend/2017-11-27/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/config/2014-11-12/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/config/2014-11-12/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/config/2014-11-12/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/cur/2017-01-06/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/cur/2017-01-06/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/cur/2017-01-06/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/datapipeline/2012-10-29/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/datapipeline/2012-10-29/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/dax/2017-04-19/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/dax/2017-04-19/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/devicefarm/2015-06-23/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/devicefarm/2015-06-23/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/devicefarm/2015-06-23/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/directconnect/2012-10-25/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/directconnect/2012-10-25/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/directconnect/2012-10-25/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/discovery/2015-11-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/discovery/2015-11-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/discovery/2015-11-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/dms/2016-01-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/dms/2016-01-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/dms/2016-01-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/ds/2015-04-16/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/ds/2015-04-16/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ds/2015-04-16/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/dynamodb/2012-08-10/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/dynamodb/2012-08-10/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/dynamodb/2012-08-10/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/dynamodb/2012-08-10/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/dynamodbstreams/2012-08-10/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/dynamodbstreams/2012-08-10/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/dynamodbstreams/2012-08-10/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/ec2/2014-09-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ec2/2014-09-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ec2/2014-09-01/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/ec2/2014-10-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ec2/2014-10-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ec2/2014-10-01/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/ec2/2015-03-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ec2/2015-03-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ec2/2015-03-01/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/ec2/2015-04-15/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ec2/2015-04-15/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ec2/2015-04-15/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/ec2/2015-10-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ec2/2015-10-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ec2/2015-10-01/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/ec2/2016-04-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ec2/2016-04-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ec2/2016-04-01/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/ec2/2016-09-15/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/ec2/2016-09-15/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ec2/2016-09-15/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ec2/2016-09-15/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/ec2/2016-11-15/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/ec2/2016-11-15/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ec2/2016-11-15/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ec2/2016-11-15/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/ecr/2015-09-21/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/ecr/2015-09-21/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ecr/2015-09-21/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/ecs/2014-11-13/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/ecs/2014-11-13/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ecs/2014-11-13/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ecs/2014-11-13/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/efs/2015-02-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/efs/2015-02-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/efs/2015-02-01/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/elasticache/2014-09-30/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/elasticache/2014-09-30/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/elasticache/2014-09-30/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/elasticache/2015-02-02/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/elasticache/2015-02-02/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/elasticache/2015-02-02/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/elasticbeanstalk/2010-12-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/elasticbeanstalk/2010-12-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/elasticbeanstalk/2010-12-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/elastictranscoder/2012-09-25/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/elastictranscoder/2012-09-25/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/elastictranscoder/2012-09-25/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/elastictranscoder/2012-09-25/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/elb/2012-06-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/elb/2012-06-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/elb/2012-06-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/elb/2012-06-01/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/elbv2/2015-12-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/elbv2/2015-12-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/elbv2/2015-12-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/emr/2009-03-31/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/emr/2009-03-31/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/emr/2009-03-31/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/emr/2009-03-31/waiters-2.json" />
        <File name="endpoints" src="lib/botocore/data/endpoints.json" />
        <File name="paginators-1" src="lib/botocore/data/es/2015-01-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/es/2015-01-01/service-2.json" />
        <File name="service-2" src="lib/botocore/data/events/2014-02-03/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/events/2015-10-07/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/events/2015-10-07/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/events/2015-10-07/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/firehose/2015-08-04/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/firehose/2015-08-04/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/firehose/2015-08-04/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/gamelift/2015-10-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/gamelift/2015-10-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/gamelift/2015-10-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/glacier/2012-06-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/glacier/2012-06-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/glacier/2012-06-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/glacier/2012-06-01/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/glue/2017-03-31/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/glue/2017-03-31/service-2.json" />
        <File name="service-2" src="lib/botocore/data/greengrass/2017-06-07/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/guardduty/2017-11-28/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/guardduty/2017-11-28/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/health/2016-08-04/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/health/2016-08-04/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/health/2016-08-04/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/iam/2010-05-08/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/iam/2010-05-08/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/iam/2010-05-08/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/iam/2010-05-08/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/importexport/2010-06-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/importexport/2010-06-01/service-2.json" />
        <File name="service-2" src="lib/botocore/data/inspector/2015-08-18/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/inspector/2016-02-16/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/inspector/2016-02-16/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/inspector/2016-02-16/service-2.json" />
        <File name="service-2" src="lib/botocore/data/iot-data/2015-05-28/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/iot-jobs-data/2017-09-29/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/iot-jobs-data/2017-09-29/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/iot/2015-05-28/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/iot/2015-05-28/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/iot/2015-05-28/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/kinesis-video-archived-media/2017-09-30/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/kinesis-video-archived-media/2017-09-30/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/kinesis-video-media/2017-09-30/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/kinesis-video-media/2017-09-30/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/kinesis/2013-12-02/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/kinesis/2013-12-02/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/kinesis/2013-12-02/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/kinesis/2013-12-02/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/kinesisanalytics/2015-08-14/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/kinesisanalytics/2015-08-14/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/kinesisanalytics/2015-08-14/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/kinesisvideo/2017-09-30/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/kinesisvideo/2017-09-30/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/kms/2014-11-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/kms/2014-11-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/kms/2014-11-01/service-2.json" />
        <File name="service-2" src="lib/botocore/data/lambda/2014-11-11/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/lambda/2015-03-31/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/lambda/2015-03-31/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/lambda/2015-03-31/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/lex-models/2017-04-19/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/lex-models/2017-04-19/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/lex-runtime/2016-11-28/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/lex-runtime/2016-11-28/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/lightsail/2016-11-28/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/lightsail/2016-11-28/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/lightsail/2016-11-28/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/logs/2014-03-28/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/logs/2014-03-28/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/logs/2014-03-28/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/machinelearning/2014-12-12/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/machinelearning/2014-12-12/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/machinelearning/2014-12-12/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/machinelearning/2014-12-12/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/marketplace-entitlement/2017-01-11/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/marketplace-entitlement/2017-01-11/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/marketplacecommerceanalytics/2015-07-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/marketplacecommerceanalytics/2015-07-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/marketplacecommerceanalytics/2015-07-01/service-2.json" />
        <File name="service-2" src="lib/botocore/data/mediaconvert/2017-08-29/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/medialive/2017-10-14/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/medialive/2017-10-14/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/mediapackage/2017-10-12/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/mediapackage/2017-10-12/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/mediastore-data/2017-09-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/mediastore-data/2017-09-01/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/mediastore/2017-09-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/mediastore/2017-09-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/meteringmarketplace/2016-01-14/examples-1.json" />
        <File name="service-2" src="lib/botocore/data/meteringmarketplace/2016-01-14/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/mgh/2017-05-31/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/mgh/2017-05-31/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/mobile/2017-07-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/mobile/2017-07-01/service-2.json" />
        <File name="service-2" src="lib/botocore/data/mq/2017-11-27/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/mturk/2017-01-17/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/mturk/2017-01-17/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/opsworks/2013-02-18/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/opsworks/2013-02-18/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/opsworks/2013-02-18/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/opsworks/2013-02-18/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/opsworkscm/2016-11-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/opsworkscm/2016-11-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/opsworkscm/2016-11-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/opsworkscm/2016-11-01/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/organizations/2016-11-28/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/organizations/2016-11-28/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/pinpoint/2016-12-01/examples-1.json" />
        <File name="service-2" src="lib/botocore/data/pinpoint/2016-12-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/polly/2016-06-10/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/polly/2016-06-10/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/polly/2016-06-10/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/pricing/2017-10-15/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/pricing/2017-10-15/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/rds/2014-09-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/rds/2014-09-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/rds/2014-09-01/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/rds/2014-10-31/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/rds/2014-10-31/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/rds/2014-10-31/service-2.json" />
        <File name="service-2.sdk-extras" src="lib/botocore/data/rds/2014-10-31/service-2.sdk-extras.json" />
        <File name="waiters-2" src="lib/botocore/data/rds/2014-10-31/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/redshift/2012-12-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/redshift/2012-12-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/redshift/2012-12-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/redshift/2012-12-01/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/rekognition/2016-06-27/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/rekognition/2016-06-27/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/rekognition/2016-06-27/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/resource-groups/2017-11-27/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/resource-groups/2017-11-27/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/resourcegroupstaggingapi/2017-01-26/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/resourcegroupstaggingapi/2017-01-26/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/route53/2013-04-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/route53/2013-04-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/route53/2013-04-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/route53/2013-04-01/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/route53domains/2014-05-15/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/route53domains/2014-05-15/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/s3/2006-03-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/s3/2006-03-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/s3/2006-03-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/s3/2006-03-01/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/sagemaker-runtime/2017-05-13/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/sagemaker-runtime/2017-05-13/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/sagemaker/2017-07-24/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/sagemaker/2017-07-24/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/sagemaker/2017-07-24/waiters-2.json" />
        <File name="paginators-1" src="lib/botocore/data/sdb/2009-04-15/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/sdb/2009-04-15/service-2.json" />
        <File name="service-2" src="lib/botocore/data/serverlessrepo/2017-09-08/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/servicecatalog/2015-12-10/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/servicecatalog/2015-12-10/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/servicecatalog/2015-12-10/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/servicediscovery/2017-03-14/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/servicediscovery/2017-03-14/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/ses/2010-12-01/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/ses/2010-12-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ses/2010-12-01/service-2.json" />
        <File name="waiters-2" src="lib/botocore/data/ses/2010-12-01/waiters-2.json" />
        <File name="examples-1" src="lib/botocore/data/shield/2016-06-02/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/shield/2016-06-02/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/shield/2016-06-02/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/sms/2016-10-24/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/sms/2016-10-24/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/sms/2016-10-24/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/snowball/2016-06-30/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/snowball/2016-06-30/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/snowball/2016-06-30/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/sns/2010-03-31/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/sns/2010-03-31/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/sns/2010-03-31/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/sqs/2012-11-05/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/sqs/2012-11-05/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/sqs/2012-11-05/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/ssm/2014-11-06/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/ssm/2014-11-06/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/ssm/2014-11-06/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/stepfunctions/2016-11-23/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/stepfunctions/2016-11-23/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/stepfunctions/2016-11-23/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/storagegateway/2013-06-30/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/storagegateway/2013-06-30/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/storagegateway/2013-06-30/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/sts/2011-06-15/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/sts/2011-06-15/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/sts/2011-06-15/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/support/2013-04-15/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/support/2013-04-15/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/support/2013-04-15/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/swf/2012-01-25/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/swf/2012-01-25/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/translate/2017-07-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/translate/2017-07-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/waf-regional/2016-11-28/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/waf-regional/2016-11-28/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/waf-regional/2016-11-28/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/waf/2015-08-24/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/waf/2015-08-24/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/waf/2015-08-24/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/workdocs/2016-05-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/workdocs/2016-05-01/service-2.json" />
        <File name="paginators-1" src="lib/botocore/data/workmail/2017-10-01/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/workmail/2017-10-01/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/workspaces/2015-04-08/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/workspaces/2015-04-08/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/workspaces/2015-04-08/service-2.json" />
        <File name="examples-1" src="lib/botocore/data/xray/2016-04-12/examples-1.json" />
        <File name="paginators-1" src="lib/botocore/data/xray/2016-04-12/paginators-1.json" />
        <File name="service-2" src="lib/botocore/data/xray/2016-04-12/service-2.json" />
        <File name="__init__" src="lib/botocore/docs/__init__.py" />
        <File name="__init__" src="lib/botocore/docs/bcdoc/__init__.py" />
        <File name="docevents" src="lib/botocore/docs/bcdoc/docevents.py" />
        <File name="docstringparser" src="lib/botocore/docs/bcdoc/docstringparser.py" />
        <File name="restdoc" src="lib/botocore/docs/bcdoc/restdoc.py" />
        <File name="style" src="lib/botocore/docs/bcdoc/style.py" />
        <File name="textwriter" src="lib/botocore/docs/bcdoc/textwriter.py" />
        <File name="client" src="lib/botocore/docs/client.py" />
        <File name="docstring" src="lib/botocore/docs/docstring.py" />
        <File name="example" src="lib/botocore/docs/example.py" />
        <File name="method" src="lib/botocore/docs/method.py" />
        <File name="paginator" src="lib/botocore/docs/paginator.py" />
        <File name="params" src="lib/botocore/docs/params.py" />
        <File name="service" src="lib/botocore/docs/service.py" />
        <File name="shape" src="lib/botocore/docs/shape.py" />
        <File name="sharedexample" src="lib/botocore/docs/sharedexample.py" />
        <File name="utils" src="lib/botocore/docs/utils.py" />
        <File name="waiter" src="lib/botocore/docs/waiter.py" />
        <File name="endpoint" src="lib/botocore/endpoint.py" />
        <File name="errorfactory" src="lib/botocore/errorfactory.py" />
        <File name="exceptions" src="lib/botocore/exceptions.py" />
        <File name="handlers" src="lib/botocore/handlers.py" />
        <File name="history" src="lib/botocore/history.py" />
        <File name="hooks" src="lib/botocore/hooks.py" />
        <File name="loaders" src="lib/botocore/loaders.py" />
        <File name="model" src="lib/botocore/model.py" />
        <File name="paginate" src="lib/botocore/paginate.py" />
        <File name="parsers" src="lib/botocore/parsers.py" />
        <File name="regions" src="lib/botocore/regions.py" />
        <File name="response" src="lib/botocore/response.py" />
        <File name="retryhandler" src="lib/botocore/retryhandler.py" />
        <File name="serialize" src="lib/botocore/serialize.py" />
        <File name="session" src="lib/botocore/session.py" />
        <File name="signers" src="lib/botocore/signers.py" />
        <File name="stub" src="lib/botocore/stub.py" />
        <File name="translate" src="lib/botocore/translate.py" />
        <File name="utils" src="lib/botocore/utils.py" />
        <File name="validate" src="lib/botocore/validate.py" />
        <File name="__init__" src="lib/botocore/vendored/__init__.py" />
        <File name="__init__" src="lib/botocore/vendored/requests/__init__.py" />
        <File name="adapters" src="lib/botocore/vendored/requests/adapters.py" />
        <File name="api" src="lib/botocore/vendored/requests/api.py" />
        <File name="auth" src="lib/botocore/vendored/requests/auth.py" />
        <File name="cacert" src="lib/botocore/vendored/requests/cacert.pem" />
        <File name="certs" src="lib/botocore/vendored/requests/certs.py" />
        <File name="compat" src="lib/botocore/vendored/requests/compat.py" />
        <File name="cookies" src="lib/botocore/vendored/requests/cookies.py" />
        <File name="exceptions" src="lib/botocore/vendored/requests/exceptions.py" />
        <File name="hooks" src="lib/botocore/vendored/requests/hooks.py" />
        <File name="models" src="lib/botocore/vendored/requests/models.py" />
        <File name="__init__" src="lib/botocore/vendored/requests/packages/__init__.py" />
        <File name="__init__" src="lib/botocore/vendored/requests/packages/chardet/__init__.py" />
        <File name="big5freq" src="lib/botocore/vendored/requests/packages/chardet/big5freq.py" />
        <File name="big5prober" src="lib/botocore/vendored/requests/packages/chardet/big5prober.py" />
        <File name="chardetect" src="lib/botocore/vendored/requests/packages/chardet/chardetect.py" />
        <File name="chardistribution" src="lib/botocore/vendored/requests/packages/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="lib/botocore/vendored/requests/packages/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="lib/botocore/vendored/requests/packages/chardet/charsetprober.py" />
        <File name="codingstatemachine" src="lib/botocore/vendored/requests/packages/chardet/codingstatemachine.py" />
        <File name="compat" src="lib/botocore/vendored/requests/packages/chardet/compat.py" />
        <File name="constants" src="lib/botocore/vendored/requests/packages/chardet/constants.py" />
        <File name="cp949prober" src="lib/botocore/vendored/requests/packages/chardet/cp949prober.py" />
        <File name="escprober" src="lib/botocore/vendored/requests/packages/chardet/escprober.py" />
        <File name="escsm" src="lib/botocore/vendored/requests/packages/chardet/escsm.py" />
        <File name="eucjpprober" src="lib/botocore/vendored/requests/packages/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="lib/botocore/vendored/requests/packages/chardet/euckrfreq.py" />
        <File name="euckrprober" src="lib/botocore/vendored/requests/packages/chardet/euckrprober.py" />
        <File name="euctwfreq" src="lib/botocore/vendored/requests/packages/chardet/euctwfreq.py" />
        <File name="euctwprober" src="lib/botocore/vendored/requests/packages/chardet/euctwprober.py" />
        <File name="gb2312freq" src="lib/botocore/vendored/requests/packages/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="lib/botocore/vendored/requests/packages/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="lib/botocore/vendored/requests/packages/chardet/hebrewprober.py" />
        <File name="jisfreq" src="lib/botocore/vendored/requests/packages/chardet/jisfreq.py" />
        <File name="jpcntx" src="lib/botocore/vendored/requests/packages/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="lib/botocore/vendored/requests/packages/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="lib/botocore/vendored/requests/packages/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="lib/botocore/vendored/requests/packages/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="lib/botocore/vendored/requests/packages/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="lib/botocore/vendored/requests/packages/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="lib/botocore/vendored/requests/packages/chardet/langthaimodel.py" />
        <File name="latin1prober" src="lib/botocore/vendored/requests/packages/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="lib/botocore/vendored/requests/packages/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="lib/botocore/vendored/requests/packages/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="lib/botocore/vendored/requests/packages/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="lib/botocore/vendored/requests/packages/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="lib/botocore/vendored/requests/packages/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="lib/botocore/vendored/requests/packages/chardet/sjisprober.py" />
        <File name="universaldetector" src="lib/botocore/vendored/requests/packages/chardet/universaldetector.py" />
        <File name="utf8prober" src="lib/botocore/vendored/requests/packages/chardet/utf8prober.py" />
        <File name="__init__" src="lib/botocore/vendored/requests/packages/urllib3/__init__.py" />
        <File name="_collections" src="lib/botocore/vendored/requests/packages/urllib3/_collections.py" />
        <File name="connection" src="lib/botocore/vendored/requests/packages/urllib3/connection.py" />
        <File name="connectionpool" src="lib/botocore/vendored/requests/packages/urllib3/connectionpool.py" />
        <File name="__init__" src="lib/botocore/vendored/requests/packages/urllib3/contrib/__init__.py" />
        <File name="ntlmpool" src="lib/botocore/vendored/requests/packages/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="lib/botocore/vendored/requests/packages/urllib3/contrib/pyopenssl.py" />
        <File name="exceptions" src="lib/botocore/vendored/requests/packages/urllib3/exceptions.py" />
        <File name="fields" src="lib/botocore/vendored/requests/packages/urllib3/fields.py" />
        <File name="filepost" src="lib/botocore/vendored/requests/packages/urllib3/filepost.py" />
        <File name="__init__" src="lib/botocore/vendored/requests/packages/urllib3/packages/__init__.py" />
        <File name="ordered_dict" src="lib/botocore/vendored/requests/packages/urllib3/packages/ordered_dict.py" />
        <File name="six" src="lib/botocore/vendored/requests/packages/urllib3/packages/six.py" />
        <File name="__init__" src="lib/botocore/vendored/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="_implementation" src="lib/botocore/vendored/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="poolmanager" src="lib/botocore/vendored/requests/packages/urllib3/poolmanager.py" />
        <File name="request" src="lib/botocore/vendored/requests/packages/urllib3/request.py" />
        <File name="response" src="lib/botocore/vendored/requests/packages/urllib3/response.py" />
        <File name="__init__" src="lib/botocore/vendored/requests/packages/urllib3/util/__init__.py" />
        <File name="connection" src="lib/botocore/vendored/requests/packages/urllib3/util/connection.py" />
        <File name="request" src="lib/botocore/vendored/requests/packages/urllib3/util/request.py" />
        <File name="response" src="lib/botocore/vendored/requests/packages/urllib3/util/response.py" />
        <File name="retry" src="lib/botocore/vendored/requests/packages/urllib3/util/retry.py" />
        <File name="ssl_" src="lib/botocore/vendored/requests/packages/urllib3/util/ssl_.py" />
        <File name="timeout" src="lib/botocore/vendored/requests/packages/urllib3/util/timeout.py" />
        <File name="url" src="lib/botocore/vendored/requests/packages/urllib3/util/url.py" />
        <File name="sessions" src="lib/botocore/vendored/requests/sessions.py" />
        <File name="status_codes" src="lib/botocore/vendored/requests/status_codes.py" />
        <File name="structures" src="lib/botocore/vendored/requests/structures.py" />
        <File name="utils" src="lib/botocore/vendored/requests/utils.py" />
        <File name="six" src="lib/botocore/vendored/six.py" />
        <File name="waiter" src="lib/botocore/waiter.py" />
        <File name="__init__" src="lib/concurrent/__init__.py" />
        <File name="__init__" src="lib/concurrent/__init__.pyc" />
        <File name="__init__" src="lib/concurrent/futures/__init__.py" />
        <File name="__init__" src="lib/concurrent/futures/__init__.pyc" />
        <File name="_base" src="lib/concurrent/futures/_base.py" />
        <File name="_base" src="lib/concurrent/futures/_base.pyc" />
        <File name="process" src="lib/concurrent/futures/process.py" />
        <File name="process" src="lib/concurrent/futures/process.pyc" />
        <File name="thread" src="lib/concurrent/futures/thread.py" />
        <File name="thread" src="lib/concurrent/futures/thread.pyc" />
        <File name="__init__" src="lib/jmespath/__init__.py" />
        <File name="ast" src="lib/jmespath/ast.py" />
        <File name="compat" src="lib/jmespath/compat.py" />
        <File name="exceptions" src="lib/jmespath/exceptions.py" />
        <File name="functions" src="lib/jmespath/functions.py" />
        <File name="lexer" src="lib/jmespath/lexer.py" />
        <File name="parser" src="lib/jmespath/parser.py" />
        <File name="visitor" src="lib/jmespath/visitor.py" />
        <File name="__init__" src="lib/s3transfer/__init__.py" />
        <File name="bandwidth" src="lib/s3transfer/bandwidth.py" />
        <File name="compat" src="lib/s3transfer/compat.py" />
        <File name="copies" src="lib/s3transfer/copies.py" />
        <File name="delete" src="lib/s3transfer/delete.py" />
        <File name="download" src="lib/s3transfer/download.py" />
        <File name="exceptions" src="lib/s3transfer/exceptions.py" />
        <File name="futures" src="lib/s3transfer/futures.py" />
        <File name="manager" src="lib/s3transfer/manager.py" />
        <File name="subscribers" src="lib/s3transfer/subscribers.py" />
        <File name="tasks" src="lib/s3transfer/tasks.py" />
        <File name="upload" src="lib/s3transfer/upload.py" />
        <File name="utils" src="lib/s3transfer/utils.py" />
    </Resources>
    <Topics />
    <IgnoredPaths>
        <Path src=".metadata" />
    </IgnoredPaths>
</Package>
